### ISSUE TITLE
How can an action process multiple requests?

### ISSUE THREAD

**Issue by shlomokraus** [mistadikay/flux-http-example#1]
Hi, great demo, thanks!

There is something I don't understand in Flux, and it is matching responses with requests.
For example, here you initiate a new search using searchAction, but the results are stored in 
the searchStore and the "search end\error" are passed as events in the dispatcher.

What if two different controllers call the search? And what if I have multiple search boxes
and I want the result to be shown only on the requesting one?

The fact that the originator of the request doesn't have control over the process (using promises for example) is an issue that confuses me in Flux architecture.

Thanks again!

**Comment by mistadikay** [comment]
Hi @shlomokraus! Good question. The short answer is: you don't need to match responses with requests, because of unidirectional data flow in Flux. 

Let me briefly describe what happens in the example first.

When `view` calls search `action` it basically just says: “I need search results for this query” and that's it, the job is done, the `view` doesn't do anything else. Before starting the search `action` tells the `store` that search is starting, `store` emits `SEARCH_START` event to the `view` and we see the loader. When results of this query will arrive, `action` will send them to the `store`, the `store` will tell the `view`: “There are search results waiting for you, go get em!” and the `view` just gets search results from the `store` and displays them. You see the chain here? View -> Action -> Store -> View — it's unidirectional.

Now, to your sub-questions.

> What if two different controllers call the search?

If you call the search while another search in progress it's up to you what to do. You can just ignore the new search while another in progress or you can cancel first search and start the new one. If needed you can dispatch something like `SEARCH_CANCELLED` to the search-store.

> And what if I have multiple search boxes and I want the result to be shown only on the requesting one?

When you have two search forms, I'm pretty sure, they search for different things, so basically you'll have two different stores and actions sets, for example `bugs-store` with `BUGS_SEARCH` action and `issues-store` with `ISSUES_SEARCH` action — so these are never interfere with each other.

Please let me know if this explanation helped you or just ask more questions. :) Also, I advice you to (re)read [Flux overview](http://facebook.github.io/flux/docs/overview.html) — it explains a lot and much better than I can do.
